### PR TITLE
fix & refactor some codes

### PR DESCRIPTION
**Pull request by Einere**
hello, i am using this library for works.
but it seems to be refactor & fix some codes.

plz consider this PR. 

(commit logs are not so pretty.. sorry.. 😓)

### fix

1. show entire waveform (`canvas`)
2. prevent changing play & pause icon when seek
3. apply performance optimization for updating current time by throttle

### refactor

1. remove unnecessary box components
2. remove manually managing "`loading` state" for markup
4. manage time state as `number`
5. separate some UI

### Note

- lint is not applied. 😅
- i'm using only `inline` mode, i didn't check vertical mode.

### CODE REVIEW

**Comment by shreyas-jadhav** [comment]
Hi, Thanks for your PR. 
Actually, I have got a busy schedule RN but I might review it soon tomorrow and let you know!
Thanks.

**Comment by Einere** [comment]
i did this PR

**Comment by shreyas-jadhav** [comment]
Hi, thanks for the refactoring changes. 
Nice to have the throttle!

It would be awesome if you could address the following issues.
I can then merge your PR and do a release.

1. In my opinion, the initial default timestamp should show `00:00` instead of `--:--`
Screenshot 2022-12-30 at 6 50 11 PM

2. Let's import only the required components from @mui/material, instead of `* from @mui/material`, yes?
3. You added an `sx` prop in `PlayPauseButton` to `IconButton`. But the user should be able to customize this. So let's merge `playPauseButtonProps.sx` and your custom sx props.


Thank you!

**Comment by Einere** [comment]
@shreyas-jadhav 

1. okay. i agree with you that initial timestamp showing `00:00`
2. okay. i will refactor using named export
3. 🆗

i will fix that things soon!

**Comment by Einere** [comment]
@shreyas-jadhav 

um... i have tried to test locally, but it shows ` Cannot find module 'mui-audio-player-plus' or its corresponding type declarations.` error...
so i didn't test the PR. sorry 😓

in addition, i added the feature that remove unreachable object for managing memory.

**Comment by shreyas-jadhav** [comment]
OK, no problem.
FYI, you needed to first link the package using `npm link ../` as stated in README.md file.
I need to continue it further, so I'm not merging in main branch. I will merge soon after doing some bug fixes.
Thank you so much for your work so far!

**Comment by Einere** [comment]
thanks to review! 👏

**Comment by shreyas-jadhav** [comment]
I have published your work in latest version.

**Pull request merged**
